SELECT *
FROM EMPLOYEES;
--Part 3 - Joins

-- 1. FIND OUT COUNTRY NAME AND REGION NAME FROM COUNTRIES AND REGION TABLE
SELECT COUNTRY_NAME, REGION_NAME
FROM COUNTRIES
INNER JOIN REGIONS
ON COUNTRIES.REGION_ID = REGIONS.REGION_ID;


-- 2. FIND OUT FIRST_NAME AND JOB_TITLE FROM JOBS AND EMPLOYEES TABLE
SELECT EMPLOYEES.FIRST_NAME,
       JOBS.JOB_TITLE
FROM EMPLOYEES
INNER JOIN JOBS
ON JOBS.JOB_ID = EMPLOYEES.JOB_ID;


-- 3. FIND OUT DEPARTMENT_NAME AND CITY
SELECT DEPARTMENTS.DEPARTMENT_NAME, LOCATIONS.CITY
FROM DEPARTMENTS
     INNER JOIN  LOCATIONS
ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID;


-- 4. FIND OUT ALL CITIES  AND COUNTRY NAMES
SELECT LOCATIONS.CITY, COUNTRIES.COUNTRY_NAME
FROM LOCATIONS
INNER JOIN COUNTRIES
ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID;


-- 5. FIND OUT FIRST_NAME, LAST NAME, DEPARTMENT ID , DEPARTMENT NAME  FOR DEPARTMENT ID 80 OR 40
SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
INNER JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
WHERE DEPARTMENTS.DEPARTMENT_ID IN (80,40);


-- 6. FIND OUT CITY , COUNTRY_NAME OF THAT CITY , REGION_NAME OF THAT CITY
SELECT LOCATIONS.CITY, COUNTRIES.COUNTRY_NAME, REGIONS.REGION_NAME
    FROM LOCATIONS
    INNER JOIN COUNTRIES
        ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
    INNER JOIN REGIONS
ON REGIONS.REGION_ID = COUNTRIES.REGION_ID;



-- 7. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY
SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.JOB_ID, DEPARTMENTS.DEPARTMENT_NAME, DEPARTMENTS.LOCATION_ID
FROM EMPLOYEES
INNER JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;


-- 8. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY , COUNTRY_NAME , REGION_NAME
SELECT EMPLOYEES.FIRST_NAME,
       JOBS.JOB_TITLE,
       DEPARTMENTS.DEPARTMENT_NAME,
       LOCATIONS.CITY,
       COUNTRIES.REGION_ID
FROM
    EMPLOYEES
        INNER JOIN
    DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
        INNER JOIN
    JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID
        INNER JOIN
    LOCATIONS ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
        INNER JOIN
    COUNTRIES ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID;




--9. FIND OUT  EMPLOYEES FIRST_NAME, LAST NAME, DEPARTMENT ID AND ALL DEPARTMENTS
--  INCLUDING  WHERE DO NOT HAVE ANY EMPLOYEE.
SELECT FIRST_NAME, LAST_NAME, DEPARTMENTS.DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES
    RIGHT JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;


--10. FIND OUT ALL DEPARTMENT_NAME  , LOCATION_ID , AND COUNTRY_ID
-- INCLUDING THOSE LOCATIONS  WITH NO DEPARTMENT
SELECT
    L.LOCATION_ID AS L,
    D.DEPARTMENT_NAME AS D,
    L.COUNTRY_ID AS C
FROM LOCATIONS L
         FULL OUTER JOIN DEPARTMENTS D
                         ON D.LOCATION_ID = L.LOCATION_ID;


--11.FIND OUT DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_NAME
-- INCLUDING THOSE COUNTRIES WITH NO DEPARTMENT
    SELECT  COUNTRIES.COUNTRY_NAME, DEPARTMENTS.DEPARTMENT_NAME, LOCATIONS.LOCATION_ID
    FROM COUNTRIES
    LEFT OUTER JOIN  LOCATIONS
   ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
    LEFT OUTER JOIN  DEPARTMENTS
    ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID;


--12. FIND OUT EMPLOYEES FIRST_NAME, DEPARTMENT ID AND DEPARTMENT NAME
-- INCLUDING THOSE DOES NOT HAVE DEPARTMENT
-- INCLUDING THOSE DEPARTMENTS  DOES NOT HAVE ANY MATCHING EMPLOYEES
SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
FULL OUTER JOIN  DEPARTMENTS
ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;