SELECT * FROM EMPLOYEES;


-- Create Table called Address
CREATE TABLE ADDRESS (
                         ADDRESS_ID INTEGER PRIMARY KEY,
                         ADDRESS VARCHAR(30) NOT NULL,
                         PHONE NUMBER NOT NULL
);

SELECT * FROM ADDRESS;

INSERT INTO ADDRESS (ADDRESS, ADDRESS_ID, PHONE) VALUES ('123 Main St', 1, 5005551111);
INSERT INTO ADDRESS (ADDRESS, ADDRESS_ID, PHONE) VALUES ('456 Main St', 2, 5005551112);
INSERT INTO ADDRESS VALUES (3, '789 Main St', 5005551113);
INSERT INTO ADDRESS VALUES (4, '101 Main St', 5005551114);
INSERT INTO ADDRESS VALUES (5, '123 Main St', 5005551115);


-- Create Table Called CUSTOMER
CREATE TABLE CUSTOMER (
                          CUSTOMER_ID INTEGER PRIMARY KEY,
                          FIRST_NAME VARCHAR(30) NOT NULL,
                          LAST_NAME VARCHAR(30) NOT NULL,
                          ADDRESS_ID INTEGER REFERENCES ADDRESS(ADDRESS_ID)
);

SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER VALUES (1, 'John', 'Doe', 1);
INSERT INTO CUSTOMER VALUES (2, 'Jane', 'Doe', null);
INSERT INTO CUSTOMER VALUES (3, 'Mike', 'Doe', 2);
INSERT INTO CUSTOMER VALUES (4, 'Jill', 'Doe', 3);
INSERT INTO CUSTOMER VALUES (5, 'Tom', 'Doe', null);


DROP TABLE CUSTOMER;
DROP TABLE ADDRESS;

COMMIT;

