SELECT * FROM EMPLOYEES;

/*
    IN
        We use the IN operator with the WHERE clause to check if a value matches any value in a list of values.
 */

SELECT * FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG' OR JOB_ID = 'FI_ACCOUNT' OR JOB_ID = 'SA_MAN';


SELECT * FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG', 'FI_ACCOUNT', 'SA_MAN');


SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID = 103 OR EMPLOYEE_ID = 104 OR EMPLOYEE_ID = 105 OR EMPLOYEE_ID = 106 OR EMPLOYEE_ID = 107;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (103, 104, 105, 106, 107);


-- GET ME ALL INFORMATION ABOUT EMPLOEES WHO ARE NOT IN THE LIST/ WHO ARE NOT HAVE EMPLOYEE_ID AS ANY OF 103.104....
SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN (103, 104, 105, 106, 107);
