SELECT * FROM EMPLOYEES;

/*
    DISTINCT Statement
        - Returns distinct (Unique) values of the specified columns.

        - SELECT DISTINCT column names separated by comma FROM table name
 */

SELECT FIRST_NAME FROM EMPLOYEES; -- 107
SELECT DISTINCT FIRST_NAME FROM EMPLOYEES; -- 92

SELECT LAST_NAME FROM EMPLOYEES; -- 107
SELECT Distinct LAST_NAME FROM EMPLOYEES; -- 102


SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES; -- 107
SELECT DISTINCT FIRST_NAME, LAST_NAME FROM EMPLOYEES; -- 107 - because this time we are looking for uniqueness of the combination of two columns


SELECT * FROM LOCATIONS;
SELECT STREET_ADDRESS FROM LOCATIONS; -- 23
SELECT DISTINCT STREET_ADDRESS FROM LOCATIONS; -- 23

SELECT POSTAL_CODE FROM LOCATIONS; -- 23
SELECT distinct POSTAL_CODE FROM LOCATIONS; -- 23

SELECT STREET_ADDRESS, POSTAL_CODE FROM LOCATIONS;
SELECT DISTINCT STREET_ADDRESS, POSTAL_CODE FROM LOCATIONS;


-- get me unique
SELECT * FROM JOBS;
SELECT JOB_TITLE FROM JOBS;
SELECT DISTINCT JOB_TITLE FROM JOBS;

SELECT MIN_SALARY FROM JOBS;
SELECT DISTINCT MIN_SALARY FROM JOBS;


SELECT FIRST_NAME FROM EMPLOYEES;
-- Get me unique names
SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;