SELECT * FROM EMPLOYEES;

/*
    VIEW
        - Virtual Tables
 */


SELECT SUBSTR(FIRST_NAME, 0, 1) || SUBSTR(LAST_NAME, 0, 1),  FIRST_NAME || ' makes $' || SALARY AS INFO FROM EMPLOYEES;


CREATE VIEW SDET -- creating Virtual Table called SDET from following query
AS SELECT SUBSTR(FIRST_NAME, 0, 1) || SUBSTR(LAST_NAME, 0, 1) AS INITIALS,  FIRST_NAME || ' makes $' || SALARY AS INFO FROM EMPLOYEES;

SELECT * FROM SDET;
SELECT INITIALS FROM SDET;
SELECT INFO FROM SDET;

--DROP VIEW SDET;