SELECT * FROM EMPLOYEES;

-- get me how many different departments we have for 'each' location_id
SELECT * FROM DEPARTMENTS;
SELECT * FROM DEPARTMENTS ORDER BY LOCATION_ID;
SELECT COUNT(*) FROM DEPARTMENTS;

SELECT LOCATION_ID FROM DEPARTMENTS;

SELECT DISTINCT LOCATION_ID FROM DEPARTMENTS; -- 7 UNIQUE LOCATION_IDS

SELECT LOCATION_ID FROM DEPARTMENTS
GROUP BY LOCATION_ID;


SELECT LOCATION_ID, COUNT(*) FROM DEPARTMENTS
GROUP BY LOCATION_ID;


SELECT LOCATION_ID, COUNT(*) FROM DEPARTMENTS
GROUP BY LOCATION_ID
ORDER BY COUNT(*); -- since we want to order by with the second column which has name 'COUNT(*)', we use it in the statement



-- We can rename the column in our result with "AS" keyword
SELECT LOCATION_ID, COUNT(*) AS TOTAL_NUM_FOR_EACH_LOCATION FROM DEPARTMENTS
GROUP BY LOCATION_ID
ORDER BY TOTAL_NUM_FOR_EACH_LOCATION;

SELECT LOCATION_ID, COUNT(*) AS "TOTAL NUM FOR EACH LOCATION" FROM DEPARTMENTS
GROUP BY LOCATION_ID
ORDER BY "TOTAL NUM FOR EACH LOCATION";